// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Adress {
	/**
	 * 
	 */
	private int adressId;
	/**
	 * 
	 */
	private String city;
	/**
	 * 
	 */
	private String localisation;
	/**
	 * 
	 */
	private String country;
	/**
	 * 
	 */
	private String street;
	/**
	 * 
	 */
	private String postalCode;
	/**
	 * 
	 */
	private String region;
}
