// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Company extends User {
	/**
	 * 
	 */
	private int companyId;
	/**
	 * 
	 */
	private String companyRcId;
	/**
	 * 
	 */
	private String companyWebsite;
}
