// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Event {
	/**
	 * 
	 */
	private int eventId;
	/**
	 * 
	 */
	private String eventName;
	/**
	 * 
	 */
	private String eventDescription;
	/**
	 * 
	 */
	private String eventImage;
	/**
	 * 
	 */
	private float eventPrice;
	/**
	 * 
	 */
	private String eventDate;
	/**
	 * 
	 */
	private String eventHourStart;
	/**
	 * 
	 */
	private int eventCapacity;
	/**
	 * 
	 */
	private String eventTags;
	/**
	 * 
	 */
	private String eventHourEnd;
	/**
	 * 
	 */
	private int userId;
	/**
	 * 
	 */
	private int adressId;
}
