// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Eventbelongstocat {
	/**
	 * 
	 */
	private int eventId;
	/**
	 * 
	 */
	private int evcatId;
	/**
	 * 
	 */
	private int eventcatId;
}
