// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Eventcategory {
	/**
	 * 
	 */
	private int evcatId;
	/**
	 * 
	 */
	private String catName;
}
