// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Eventparticipated {
	/**
	 * 
	 */
	private int eventParticipateId;
	/**
	 * 
	 */
	private int eventId;
	/**
	 * 
	 */
	private int userId;
}
