// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Order {
	/**
	 * 
	 */
	private int OrderId;
	/**
	 * 
	 */
	private float ToTalprice;
	/**
	 * 
	 */
	private String OrderDate;
	/**
	 * 
	 */
	private int userId;
}
