// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Panier {
	/**
	 * 
	 */
	private int panierId;
	/**
	 * 
	 */
	private String dateAdded;
	/**
	 * 
	 */
	private int quantity;
	/**
	 * 
	 */
	private int eventId;
}
