// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class Particulier extends User {
	/**
	 * 
	 */
	private int particulierId;
	/**
	 * 
	 */
	private String particulierSurname;
	/**
	 * 
	 */
	private String particulierBirthDate;
	/**
	 * 
	 */
	private int particulierCin;
}
