// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BlaanOut;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	private int userId;
	/**
	 * 
	 */
	private String userName;
	/**
	 * 
	 */
	private String userPhone;
	/**
	 * 
	 */
	private String userPassword;
	/**
	 * 
	 */
	private String userUsername;
	/**
	 * 
	 */
	private int userLanguage;
	/**
	 * 
	 */
	private String userMailAdress;
	/**
	 * 
	 */
	private String userRegistrationDate;
	/**
	 * 
	 */
	private int adressId;
	/**
	 * 
	 */
	private int panierId;
}
